"""FastAPI app factory for the JAI control plane (COCKPIT backend).

Every endpoint degrades gracefully: when Postgres is unreachable, data routes
answer 503 with a JSON error envelope and /health answers 200 with
``postgres: false`` — the console never sees a raw stack trace.
"""

from __future__ import annotations

import os
from functools import lru_cache
from typing import Annotated, Any, Literal

import psycopg
import uvicorn
from fastapi import FastAPI, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel

from jai_api import chat, queries
from jai_api.db import ping


class DecideRequest(BaseModel):
    approver: str
    approve: bool
    note: str = ""


class OrchestrateRequest(BaseModel):
    title: str
    category: str = "Safety Equipment & PPE"
    est_value_usd: float = 120000
    tenant_id: str = "TEN-0001"
    role: str = "cpo"
    auto_approve: bool = True


class NegotiateRequest(BaseModel):
    list_price: float = 100000
    seller: int = 0  # index into the fleet's seller personas
    tenant_id: str = "TEN-0001"
    role: str = "cpo"


class ManifestValidateRequest(BaseModel):
    yaml: str


# EU AI Act Article 50 transparency disclosure — surfaced in the console.
TRANSPARENCY = {
    "ai_system": True,
    "notice": (
        "You are interacting with the JAI agentic AI platform. Responses are generated by "
        "autonomous AI agents. Agents act only within their assigned permissions and a "
        "bounded mandate; every action is recorded in a tamper-evident audit log and "
        "high-impact actions require human approval."
    ),
    "regulation": "EU AI Act, Article 50 (transparency of AI systems)",
    "data": "All data in this deployment is synthetic.",
    "human_oversight": "Human-in-the-loop gates (jai-brakes) and kill switches apply.",
}

Dimension = Literal["tenant_id", "agent", "run_id", "model_group"]


def _pg_unavailable(exc: Exception) -> JSONResponse:
    return JSONResponse(
        status_code=503,
        content={"error": "postgres_unavailable", "detail": str(exc).strip()},
    )


@lru_cache(maxsize=1)
def _fleet() -> Any:
    """The orchestration fleet, built once and reused across /orchestrate calls."""
    from jai_api.fleet import build_fleet

    return build_fleet()


def create_app() -> FastAPI:
    """Build the read-only control-plane app the console talks to."""
    app = FastAPI(
        title="jai-api",
        version="0.1.0",
        description="JAI control plane — read-only: costs, runs, audit verification, health.",
    )
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["http://localhost:3000", "http://127.0.0.1:3000"],
        allow_methods=["GET", "POST"],
        allow_headers=["*"],
    )

    @app.get("/health")
    def health() -> dict[str, Any]:
        return {"status": "ok", "postgres": ping()}

    @app.get("/costs")
    def costs(by: Annotated[Dimension, Query()] = "tenant_id") -> Any:
        try:
            return queries.costs_by(by)
        except (psycopg.Error, OSError) as exc:
            return _pg_unavailable(exc)

    @app.get("/runs")
    def runs(limit: Annotated[int, Query(ge=1, le=500)] = 20) -> Any:
        try:
            return queries.list_runs(limit)
        except (psycopg.Error, OSError) as exc:
            return _pg_unavailable(exc)

    @app.get("/runs/{run_id}/events")
    def events_for_run(run_id: str) -> Any:
        try:
            return queries.run_events(run_id)
        except (psycopg.Error, OSError) as exc:
            return _pg_unavailable(exc)

    @app.get("/audit/verify")
    def audit_verify() -> Any:
        try:
            return queries.verify_chain()
        except (psycopg.Error, OSError) as exc:
            return _pg_unavailable(exc)

    @app.get("/meta")
    def meta() -> Any:
        try:
            tenants = queries.tenants()
        except (psycopg.Error, OSError):
            tenants = []  # cortex not ingested yet — the console renders a hint
        return {"tenants": tenants, "roles": ["requester", "category_manager", "cpo"]}

    @app.post("/chat")
    def post_chat(req: chat.ChatRequest) -> Any:
        try:
            return chat.run_chat(req)
        except FileNotFoundError as exc:
            return JSONResponse(status_code=503, content={"error": "agent_unavailable",
                                                          "detail": str(exc)})
        except (psycopg.Error, OSError) as exc:
            return _pg_unavailable(exc)

    @app.get("/registry")
    def registry() -> Any:
        try:
            from jai_registry import Registry

            reg = Registry()
            reg.ensure_schema()
            records = reg.list()
            if not records:  # first run — sync from disk so the fleet is visible
                from jai_api.fleet import AGENT_SYSTEMS, AGENTS, RESULTS

                reg.sync_agents(AGENTS, AGENT_SYSTEMS)
                if RESULTS.exists():
                    reg.load_scorecards(RESULTS)
                records = reg.list()
            return [r.model_dump(mode="json") for r in records]
        except (psycopg.Error, OSError) as exc:
            return _pg_unavailable(exc)

    @app.get("/network")
    def network() -> Any:
        from jai_api.fleet import network_topology

        return network_topology()

    @app.post("/orchestrate")
    def orchestrate(req: OrchestrateRequest) -> Any:
        try:
            from jai_manifest import Actor, RunContext

            from jai_api.fleet import run_orchestration

            fleet = _fleet()
            ctx = RunContext(tenant_id=req.tenant_id, actor=Actor(id="console", role=req.role))
            intake = {
                "title": req.title, "category": req.category,
                "est_value_usd": req.est_value_usd,
                "line_items": [{"sku": "REQ", "qty": 1}],
                "requested_by": "console", "simulate_bids": 3,
            }
            return run_orchestration(fleet, ctx, intake, auto_approve=req.auto_approve)
        except (psycopg.Error, OSError) as exc:
            return _pg_unavailable(exc)

    @app.post("/negotiate")
    def negotiate(req: NegotiateRequest) -> Any:
        try:
            from jai_manifest import Actor, RunContext

            from jai_api.fleet import run_negotiation

            fleet = _fleet()
            sellers = fleet.sellers
            if not sellers:
                return JSONResponse(status_code=503, content={"error": "no_sellers",
                                                              "detail": "fleet has no sellers"})
            seller = sellers[req.seller % len(sellers)]
            ctx = RunContext(tenant_id=req.tenant_id, actor=Actor(id="console", role=req.role))
            payload = run_negotiation(fleet, ctx, {"list_price": req.list_price,
                                                   "seller_skill": seller["skill_id"]})
            payload["sellers"] = sellers
            return payload
        except (psycopg.Error, OSError) as exc:
            return _pg_unavailable(exc)

    @app.get("/maturity")
    def maturity() -> Any:
        from jai_api.fleet import maturity_ladder

        return maturity_ladder()

    @app.get("/transparency")
    def transparency() -> Any:
        return TRANSPARENCY

    @app.post("/manifest/validate")
    def manifest_validate(req: ManifestValidateRequest) -> Any:
        import yaml as _yaml
        from jai_manifest import AgentManifest

        try:
            data = _yaml.safe_load(req.yaml)
            manifest = AgentManifest.model_validate(data)
        except Exception as exc:  # noqa: BLE001 — surface any validation error to the studio
            return {"valid": False, "error": str(exc)}
        return {"valid": True, "name": manifest.name,
                "autonomy_level": int(manifest.autonomy_level), "pipeline": manifest.pipeline,
                "skills": manifest.skills}

    @app.get("/approvals")
    def approvals(tenant_id: str | None = None) -> Any:
        try:
            from jai_brakes import Brakes

            brakes = Brakes()
            brakes.ensure_schema()
            return brakes.pending(tenant_id)
        except (psycopg.Error, OSError) as exc:
            return _pg_unavailable(exc)

    @app.post("/approvals/{approval_id}/decide")
    def decide_approval(approval_id: int, req: DecideRequest) -> Any:
        try:
            from jai_brakes import Brakes

            row = Brakes().decide(approval_id, approver=req.approver,
                                  approve=req.approve, note=req.note)
            return row
        except ValueError as exc:  # already decided / unknown id
            return JSONResponse(status_code=409, content={"error": "undecidable",
                                                          "detail": str(exc)})
        except (psycopg.Error, OSError) as exc:
            return _pg_unavailable(exc)

    return app


def serve() -> None:
    """Console-script entrypoint: uvicorn on PORT (default 8400)."""
    uvicorn.run(
        create_app(),
        host=os.environ.get("HOST", "127.0.0.1"),
        port=int(os.environ.get("PORT", "8400")),
    )
